// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1yu3L5SwirpZl5MdUI1w88OM3WchyPQU',
    appId: '1:258251317965:web:7ddbc124059b4b38ab7f84',
    messagingSenderId: '258251317965',
    projectId: 'delivery-app-eee54',
    authDomain: 'delivery-app-eee54.firebaseapp.com',
    storageBucket: 'delivery-app-eee54.firebasestorage.app',
    measurementId: 'G-9Q72E8WD9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDso3dCoah3zVoTHFzz62sbF50xpjZ9nFY',
    appId: '1:258251317965:android:347842abf7e60888ab7f84',
    messagingSenderId: '258251317965',
    projectId: 'delivery-app-eee54',
    storageBucket: 'delivery-app-eee54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhZf8bTY2dno-OiFGwsyhNnRL35sOlBZw',
    appId: '1:258251317965:ios:3485e26471622063ab7f84',
    messagingSenderId: '258251317965',
    projectId: 'delivery-app-eee54',
    storageBucket: 'delivery-app-eee54.firebasestorage.app',
    iosBundleId: 'com.example.deliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhZf8bTY2dno-OiFGwsyhNnRL35sOlBZw',
    appId: '1:258251317965:ios:3485e26471622063ab7f84',
    messagingSenderId: '258251317965',
    projectId: 'delivery-app-eee54',
    storageBucket: 'delivery-app-eee54.firebasestorage.app',
    iosBundleId: 'com.example.deliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1yu3L5SwirpZl5MdUI1w88OM3WchyPQU',
    appId: '1:258251317965:web:a16b2a3672aa05f9ab7f84',
    messagingSenderId: '258251317965',
    projectId: 'delivery-app-eee54',
    authDomain: 'delivery-app-eee54.firebaseapp.com',
    storageBucket: 'delivery-app-eee54.firebasestorage.app',
    measurementId: 'G-LSEV4TK808',
  );
}
