// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCOs6maevvtSOAZfv5LKFZ_Kn9N9Jgs9o',
    appId: '1:817766084219:web:f43db793085075c5667cde',
    messagingSenderId: '817766084219',
    projectId: 'playground-36167',
    authDomain: 'playground-36167.firebaseapp.com',
    storageBucket: 'playground-36167.firebasestorage.app',
    measurementId: 'G-P33Z4TDM45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_VSOxka-BCFSc-fKh_UBnHY3bQrjVuHU',
    appId: '1:817766084219:android:033506820891a6c0667cde',
    messagingSenderId: '817766084219',
    projectId: 'playground-36167',
    storageBucket: 'playground-36167.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbhB4ShkVHAIqG6tAH68yTyAQmZVK6TDo',
    appId: '1:817766084219:ios:f5375a4b53dc0842667cde',
    messagingSenderId: '817766084219',
    projectId: 'playground-36167',
    storageBucket: 'playground-36167.firebasestorage.app',
    iosBundleId: 'com.example.deliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbhB4ShkVHAIqG6tAH68yTyAQmZVK6TDo',
    appId: '1:817766084219:ios:f5375a4b53dc0842667cde',
    messagingSenderId: '817766084219',
    projectId: 'playground-36167',
    storageBucket: 'playground-36167.firebasestorage.app',
    iosBundleId: 'com.example.deliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCOs6maevvtSOAZfv5LKFZ_Kn9N9Jgs9o',
    appId: '1:817766084219:web:8bb179a95ea46ee2667cde',
    messagingSenderId: '817766084219',
    projectId: 'playground-36167',
    authDomain: 'playground-36167.firebaseapp.com',
    storageBucket: 'playground-36167.firebasestorage.app',
    measurementId: 'G-REWW432D93',
  );

}